# Generated by Django 4.2.5 on 2023-12-15 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('pargraph', models.TextField(blank=True, null=True)),
                ('auth_name', models.TextField(blank=True, null=True)),
                ('auth_image', models.ImageField(upload_to='uploads/gallery/')),
            ],
        ),
    ]
