# Generated by Django 4.2.5 on 2023-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='auth_image',
            field=models.ImageField(upload_to='uploads/blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='uploads/blog/'),
        ),
    ]
