# Generated by Django 4.2.5 on 2023-12-13 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('what_include', models.TextField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('in_addition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
