# Generated by Django 4.2.5 on 2023-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_feedback_rating_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatar/'),
        ),
    ]
