# Generated by Django 4.2.5 on 2023-12-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_feedback_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/'),
        ),
    ]
