# Generated by Django 4.2.5 on 2023-12-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_image_1_alter_service_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='in_addition',
        ),
    ]
