# Generated by Django 4.2.5 on 2023-12-16 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_icon_whychooseourservices_icon_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
