# Generated by Django 4.2.5 on 2023-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_gallery_image_1_alter_gallery_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homeGallery/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/'),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/'),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/'),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/'),
        ),
        migrations.AlterField(
            model_name='whychooseourservices',
            name='icon_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/whyOurServices/'),
        ),
    ]
