# Generated by Django 4.2.5 on 2023-12-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_title', models.CharField(blank=True, max_length=200, null=True)),
                ('main_top', models.CharField(blank=True, max_length=800, null=True)),
                ('main_bottom', models.CharField(blank=True, max_length=800, null=True)),
                ('paragraph_title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_title_2', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_title_3', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_title_4', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('paragraph_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('paragraph_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('paragraph_4', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
