# Generated by Django 4.2.5 on 2023-12-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_paragraph_1_alter_about_paragraph_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/about/'),
        ),
    ]
